spring:
  kafka:
    bootstrap-servers: ${KAKFA_URL:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  data:
    redis:
      host: ${REDIS_IP:localhost}
      port: 6397
#      host: 10.0.0.138
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:ums}
    #url: jdbc:h2:file:/app/db/schedule;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        generate-ddl: true
logging:
  file:
    name: /app/logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:.ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,metrics,busrefresh
  endpoint:
    health:
      show-details: always
    env:
      keys-to-sanitize: ""